---
- name: update config/unicorn.rb
  replace: 
    path: "{{ app_dir }}/config/unicorn.rb"
    regexp: |
      listen '/home/ec2-user/raisetech-live8-sample-app/unicorn.sock'
      pid    '/home/ec2-user/raisetech-live8-sample-app/unicorn.pid'
    replace: |
      listen '{{ app_dir }}/unicorn.sock'
      pid    '{{ app_dir }}/unicorn.pid'

- name: avoid blocked host error
  blockinfile:
    path: "{{ app_dir }}/config/environments/development.rb"
    insertbefore: end
    block: "  config.hosts << \"{{ (lookup('env','AWS_ALB')) }}\""
